Added step to handle non zero exit code from TF plan

diff --git a/.github/workflows/terraform-core.yml b/.github/workflows/terraform-core.yml
--- a/.github/workflows/terraform-core.yml
+++ b/.github/workflows/terraform-core.yml
@@ -314,6 +314,7 @@ jobs:
       - name: Terraform Plan
         id: tf_plan
         working-directory: "${{ matrix.stack.directory }}"
+        continue-on-error: true
         if: steps.download_plan.conclusion == 'skipped' && steps.state_empty.outputs.skip_workflow == 'false' 
         env:
           ENVIRONMENT_NAME: "${{ inputs.environment_name }}"
@@ -328,9 +329,10 @@ jobs:
           if [[ "$TERRAFORM_ACTION" == "destroy" ]]; then
             terraform plan -lock-timeout=5m -destroy -no-color -input=false -out=tfplan -compact-warnings ${TERRAFORM_VARIABLES}
           else
+            echo "Terraform variables: $TERRAFORM_VARIABLES"
             terraform plan -lock-timeout=5m -no-color -input=false -out=tfplan -detailed-exitcode -compact-warnings ${TERRAFORM_VARIABLES}
             terraform_exit_code=$?
-            echo "Terraform exit code: $terraform_exit_code"
+            echo "terraform_exit_code=$terraform_exit_code" >> $GITHUB_OUTPUT
 
             # If no changes are required, we can skip subsequent steps for this stack.
             if [ $terraform_exit_code -eq 0 ]; then
@@ -346,6 +348,14 @@ jobs:
           
           echo "planned_changes=$planned_changes" >> $GITHUB_OUTPUT
           
+      - name: Check Terraform plan exit code
+        run: |
+          # Separate step required otherwise GitHub will exit on non-zero exit code.
+          if [ "$terraform_exit_code" -eq 1 ]; then
+            echo "Terraform encountered an error. Exiting workflow."
+            exit 1
+          fi
+
       - name: Update stack matrix
         working-directory: "${{ matrix.stack.directory }}"
         run: |
